routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('login', 'LoginController@index')->name('login');
Route::post('login', 'LoginController@login')->name('login')->middleware("throttle:2,2");
Route::post('logout', 'LoginController@logout')->name('logout');

Route::group(['middleware' => 'auth'], function () {
    Route::resource('users', 'UserController');
    Route::get('/home', 'HomeController@index')->name('home');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\softDeletes;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Support\Facades\Hash;

class User extends Model
{
    use SoftDeletes;

    protected $table = 'users';
    protected $perPage = 20;
    const ADMIN = 1;
    const STAFF = 2;
    protected $fillable = [
        'id', 
        'mail_address', 
        'password', 
        'name', 
        'address', 
        'phone',
        'role',
        'class_id'
    ];

    /**
     * belongTo classroom
     */
    public function classroom()
    {
        return $this->belongsTo('App\Models\Classroom', 'class_id');
    }

    /**
     * Scope a query to get user.
     *
     * @param \Illuminate\Database\Eloquent\Builder $query
     * @param mixed $type
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeGetListUser($query, $searchUser) 
    {
        return $query->where($searchUser);
    }

    /**
     * Search and get data in database
     * 
     * @return array|null
     */
    public function getUsers($request)
    {
        $searchUser = [
            ['mail_address', 'like', '%' . $request->input('txtEmail') . '%'],
            ['name', 'like', '%' . $request->input('txtName') . '%'],
            ['address', 'like', '%' . $request->input('txtAddress') . '%'],
        ];
        if ($request->input('txtPhone') != null) {
            $searchUser[] = ['phone', '=', $request->input('txtPhone')];
        }
        if ($request->input('class') != null) {
            $searchUser[] = ['class_id', '=', $request->input('class')];
        }
        $user = $this->with('classroom')->getListUser($searchUser)->orderby('mail_address')->paginate();
        return $user;
    }

    /**
     * store user
     * 
     * @param $user
     * @return bool
     */
    public function storeUser($user)
    {
        $user['password'] = Hash::make($user['password']);
        $store = $this->create($user);
        if ($store) {
            return true;
        } else {
            return false;
        }
    }

    /**
     * get detail user
     * 
     * @param int $id
     * @return array|null
     */
    public function getDetailUser($id)
    {
        return $this->find($id);
    }

    /**
     * update user
     * 
     * @return bool
     */
    public function updateUser($id, $request)
    {
        $request['password'] != null ? $request['password'] = Hash::make($request['password']) : $request = array_filter($request, 'strlen');
        $update = $this->find($id)->update($request);
        if ($update) {
            return true;
        } else {
            return false;
        }
    }

}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Session;
use Illuminate\Support\Facades\Hash;
use App\Http\Requests\CreateUserRequest;
use App\Models\User;
use App\Models\Classroom;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Auth;
use App\Events\RegisteredUser;

class UserController extends Controller
{

    protected $user;
    protected $class;

    /**
    * function construct controller
    *
    * @return void
    */
    public function __construct(User $user, Classroom $class)
    {
        $this->user = $user;
        $this->class = $class;
        $this->middleware('checkclass');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $data = $this->user->getUsers($request);
        $classList = $this->class->getClass();
        $request->flash();
        return view('user.index', compact(['data', 'classList']));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->authorize('isAdmin');
        $classList = $this->class->getClass();
        return view('user.create', compact('classList'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateUserRequest $request)
    {
        $this->authorize('isAdmin');
        $check = $this->user->storeUser($request->all());
        if ($check) {
            Session::flash('message', 'Thêm mới thành công!');
            event(new RegisteredUser($request));
            return redirect()->route('users.index');
        } else {
            Session::flash('message', 'Thêm mới không thành công!');
            return redirect()->back();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {   
        $this->authorize('isAdmin');
        $detailUser = $this->user->getDetailUser($id);
        return view('user.create', compact('detailUser'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CreateUserRequest $request, $id)
    {
        $this->authorize('isAdmin');
        $user = $this->user->updateUser($id, $request->all());
        if ($user) {
            Session::flash('message', 'Cập nhật thành công!');
            return redirect()->route('users.index');
        } else {
            Session::flash('message', 'Cập nhật không thành công!');
            return redirect()->back()->withInput();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

}

resources/views/user/create.blade.php
@extends('layouts.default')

@section('title')
    {{ isset($detailUser) ? 'Edit' : 'Create' }}
@endsection

@section('content')
<div class="container">
    @if (Session::has('message'))
        <div class="alert alert-danger">{{ Session::get('message') }}</div>
    @endif
    <form action="{{ isset($detailUser) ? route('users.update', $detailUser->id) : route('users.store') }}" method="POST">
        @csrf
        @isset($detailUser)
            @method('PUT')
        @endisset
        <div class="row">
            <h4 class="col-12">{{ isset($detailUser) ? 'Cập nhật' : 'Thêm mới' }}</h4>
            <div class="col-6">
                <label class="@error('mail_address') text-danger @enderror">Địa chỉ mail</label>
                <input type="email" placeholder="Email" name="mail_address" class="form-control @error('mail_address') border border-danger @enderror" value="{{ old('mail_address', isset($detailUser) ? $detailUser->mail_address : '') }}">
                @error('mail_address')
                    <div class="text-danger">{{ $message }}</div>
                @enderror
            </div>
            <div class="col-6">
                <label class="@error('password') text-danger @enderror">Mật khẩu</label>
            <input type="password" name="password" class="form-control @error('password') border border-danger @enderror">
                @error('password')
                    <div class="text-danger">{{ $message }}</div>
                @enderror
            </div>
            <div class="col-6">
                <label class="@error('password_confirmation') text-danger @enderror">Mật khẩu xác nhận</label>
            <input type="password" name="password_confirmation" class="form-control @error('password_confirmation') border border-danger @enderror">
                @error('password_confirmation')
                    <div class="text-danger">{{ $message }}</div>
                @enderror
            </div>
            <div class="col-6">
                <label class="@error('name') text-danger @enderror">Tên</label>
                <input type="text" name="name" class="form-control @error('name') border border-danger @enderror" value="{{ old('name', isset($detailUser) ? $detailUser->name : '') }}">
                @error('name')
                    <div class="text-danger">{{ $message }}</div>
                @enderror
            </div>
            <div class="col-6">
                <label class="@error('address') text-danger @enderror">Địa chỉ</label>
                <input type="text" name="address" class="form-control @error('address') border border-danger @enderror" value="{{ old('address', isset($detailUser) ? $detailUser->address : '') }}">
                @error('address')
                    <div class="text-danger">{{ $message }}</div>
                @enderror
            </div>
            <div class="col-6">
                <label class="@error('phone') text-danger @enderror">Số điện thoại</label>
                <input type="text" name="phone" class="form-control @error('phone') border border-danger @enderror" value="{{ old('phone', isset($detailUser) ? $detailUser->phone : '') }}">
                @error('phone')
                    <div class="text-danger">{{ $message }}</div>
                @enderror
            </div>
            <div class="col-6">
                <label>Vai trò</label>
                <select class="form-control" name="role">
                    <option value="{{ User::ADMIN }}">Quản trị viên</option>
                    <option value="{{ User::STAFF }}">Nhân viên</option>
                </select>
            </div>
            <div class="col-6">
                <label>Lớp</label>
                <select class="form-control" name="class_id">
                    @foreach ($classList as $item)
                        <option value="{{ $item->id }}">{{ $item->name }}</option>
                    @endforeach
                </select>
            </div>
            <input type="hidden" value="{{ isset($detailUser) ? $detailUser->id : '' }}" name="id">
            <div class="col-12 pt-2 text-center">
                <input type="submit" value="{{ isset($detailUser) ? 'Cập nhật' : 'Thêm mới' }}" class="btn btn-warning">
            </div>
        </div>
    </form>
    
</div>
@endsection

resources/views/user/index.blade.php
@extends('layouts.default')

@section('title')
    Index
@endsection

@section('content')
    <div class="container-fluid">
        <div class="p-3 mb-3 bg-white rounded mx-3" style="box-shadow: 0 .125rem .25rem rgba(0,0,0,.075)!important;">
            <h4>Tìm kiếm</h4>
            <form action="{{ route('users.index') }}" method="GET">
                <div class="row">
                    <div class="col-2">
                        <input type="text" placeholder="Email" class="form-control" name="txtEmail"
                            value="{{ old('txtEmail') }}">
                    </div>
                    <div class="col-2">
                        <input type="text" placeholder="Name" class="form-control" name="txtName"
                            value="{{ old('txtName') }}">
                    </div>
                    <div class="col-3">
                        <input type="text" placeholder="Address" class="form-control" name="txtAddress"
                            value="{{ old('txtAddress') }}">
                    </div>
                    <div class="col-2">
                        <input type="text" placeholder="Phone" class="form-control" name="txtPhone"
                            value="{{ old('txtPhone') }}">
                    </div>
                    <div class="col-2">
                        <select class="form-control" name="class">
                            @foreach ($classList as $item)
                                <option value="{{ $item->id }}">{{ $item->name }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="col-1">
                        <input type="submit" class="btn btn-success" value="Tìm kiếm">
                    </div>
                </div>
            </form>
        </div>
        <div class="p-3 mb-5 bg-white rounded mx-3" style="box-shadow: 0 .125rem .25rem rgba(0,0,0,.075)!important;">
            <div class="mb-2 row">
                @if(Session::has('message'))
                    <div class="alert  alert-success col-12">{{ Session::get('message') }}</div>
                @endif
                @can('isAdmin')
                    <div class="col-1">
                        <a href="{{ route('users.create') }}" class="btn btn-warning">Thêm mới</a>
                    </div>
                @endcan
            </div>
            <table class="table">
                <thead class="text-center">
                    <th>STT</th>
                    <th>Địa chỉ Mail</th>
                    <th>Tên</th>
                    <th>Địa chỉ</th>
                    <th>Số điện thoại</th>
                    <th>Lớp</th>
                    <th>Hành động</th>
                </thead>
                <tbody>
                    @if(count($data) > 0)
                        @foreach($data as $key => $item)
                            <tr>
                                <td>
                                    {{ $key + ($data->currentPage() - 1) * $data->perPage() + 1 }}
                                </td>
                                <td>{{ $item->mail_address }}</td>
                                <td>{{ Helper::toUpperCase($item->name) }}</td>
                                <td>{{ $item->address }}</td>
                                <td>{{ $item->phone }}</td>
                                <td>{{ $item->classroom->name }}</td>
                                <td>
                                    @can('isAdmin')
                                        <a href="{{ route('users.edit', $item->id) }}" class="btn btn-primary">Cập nhật</a>
                                    @endcan
                                </td>
                            </tr>
                        @endforeach
                    @else
                        <tr>
                            <td colspan="6" class="text-center">Không có dữ liệu</td>
                        </tr>
                    @endif
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="6"> {!! $data->links() !!}</td>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
@endsection